### ISSUE TITLE
Change package from `com.hpe.sbt` to `com.github.sbt`

### ISSUE THREAD

**Issue by mdedetrich** [sbt/sbt-pull-request-validator#22]
The package is still [`com.hpe.sbt`](https://github.com/sbt/sbt-pull-request-validator/blob/main/src/main/scala/com/hpe/sbt/ValidatePullRequest.scala#L17), I can change it to `com.github.sbt` with the same trick that was used [here](https://github.com/sbt/sbt-osgi/pull/127/files#diff-83874d8aee7334526e88d819899435fdf569e125847943564d5ea6d12ddac0e8) to maintain source compatibility, should we do it now? A counter argument for this can be that its technically breaking binary compatibility and the plugin already has `1` as its major in version but I also don't think it strictly follows SemVer and I am not aware of any sbt plugins that depend on this plugin which is the only case where SemVer would practically matter.

And if so what version should I use in the deprecated annotation, I assume `1.1.0` will be our next release?

@mkurz @eed3si9n @gmethvin

**Comment by mkurz** [comment]
> I can change it to `com.github.sbt` with the same trick that was used [here](https://github.com/sbt/sbt-osgi/pull/127/files#diff-83874d8aee7334526e88d819899435fdf569e125847943564d5ea6d12ddac0e8)

I like that. Actually for all the plugins for which I changed to groupId to `com.github.sbt` recently (mostly from `com.typesafe.sbt`) I did _not_ change the package names, but kept them like they were (again, mostly `com.typesafe.sbt`). I might start to migrate the package names using the same approach you used in one of the next releases of those plugins, whenever I have time. My primary goal was to have them published to maven central anyway.
Also, for many plugins I just bumped the version to 2.0.0, so you could probably just do the same. I know there are different opinions/views about how versioning should be handled "correctly", for what's worth, I just didn't care so much for the plugins I recently migrated, because IMHO versions are cheap (just talking about the sbt plugins here, not about how we handle versioning in Play and other projects).

**Comment by mdedetrich** [comment]
PR made at https://github.com/sbt/sbt-pull-request-validator/pull/26
